# Generated by Django 5.2.3 on 2025-06-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_depth', models.IntegerField(default=2)),
                ('exclude_urls', models.TextField(blank=True, help_text='Comma-separated URLs to exclude')),
                ('enable_alerts', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.CharField(max_length=100, unique=True)),
                ('target_url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('spider_running', 'Spider Running'), ('spider_complete', 'Spider Complete'), ('scan_running', 'Scan Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('spider_progress', models.IntegerField(default=0)),
                ('scan_progress', models.IntegerField(default=0)),
                ('total_progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='XSSScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.CharField(max_length=255)),
                ('risk', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
