# Generated by Django 5.1.7 on 2025-06-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xss_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerconfig',
            name='enable_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scannerconfig',
            name='enable_toast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scannerconfig',
            name='timeout',
            field=models.IntegerField(default=60, help_text='Scan timeout in seconds'),
        ),
    ]
