# Generated by Django 5.2.3 on 2025-06-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('param', models.CharField(max_length=255)),
                ('risk', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
