# Generated by Django 5.2.3 on 2025-06-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_logs', '0002_sqlscanlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLScanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.CharField(max_length=100, unique=True)),
                ('target_url', models.URLField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('spider_progress', models.IntegerField(default=0)),
                ('scan_progress', models.IntegerField(default=0)),
                ('total_progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
